name: Run pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Test with Python
        run: uv run --frozen pytest
